#!/bin/bash
set -e

echo "[INFO] Stopping raspi-server service..."

# Stop service if running
systemctl stop raspi-server.service || true

# Disable service
systemctl disable raspi-server.service || true

# Reload systemd
systemctl daemon-reload

echo "[INFO] raspi-server service removed."
